import { SearchCheck, Lightbulb, PanelsTopLeft, MonitorSmartphone, MessagesSquare, ShieldCheck, LifeBuoy, Compass, ListChecks, Sparkles } from 'lucide-react'
import SEO from '../components/SEO'
import { PageHero, SectionTitle, IconCard, CTA } from '../components/UI'

export default function WhyUs() {
  const tones = ['blue','violet','green','coral','amber','cyan','violet']
  const reasons = [
    [SearchCheck,'Understand Before Building','Every project should begin with a clear understanding of the business and requirements.'],[Lightbulb,'Simple Solutions','Avoid unnecessary complexity and focus on what actually provides value.'],[PanelsTopLeft,'Professional Design','Create clean interfaces that represent the business professionally.'],[MonitorSmartphone,'Responsive Experience','Ensure websites work properly across different screen sizes.'],[MessagesSquare,'Clear Communication','Keep clients informed throughout the project.'],[ShieldCheck,'Reliable Development','Build solutions with attention to usability and maintainability.'],[LifeBuoy,'Support','Provide assistance when updates or improvements are required.']
  ]
  return <><SEO title="Why Us | Youpeak Tech" description="Discover Youpeak Tech's practical, transparent and business-focused approach to digital solutions."/><PageHero eyebrow="Why Youpeak Tech" title="Why Choose Youpeak Tech?" text="We focus on creating simple, professional and reliable digital solutions designed around real business requirements."/>
    <section className="section-space"><div className="container-site"><SectionTitle eyebrow="Key advantages" title="A Clear, Business-Focused Approach" text="Good technology starts with the right priorities. These principles guide how we approach every solution."/><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{reasons.map(([icon,title,text],i)=><IconCard key={title} icon={icon} title={title} text={text} tone={tones[i]} delay={(i%3)*80}/>)}</div></div></section>
    <section className="section-wash section-space"><div className="container-site grid items-center gap-10 lg:grid-cols-[.9fr_1.1fr] lg:gap-20"><div><SectionTitle eyebrow="Working Principles" title="Thoughtful at Every Step" text="We keep the process easy to follow and make decisions based on what the business and its users actually need."/></div><div className="grid gap-4 sm:grid-cols-3">{[[Compass,'Purpose first','Start with the goal, not the feature list.'],[ListChecks,'Keep it clear','Make each step understandable and focused.'],[Sparkles,'Refine carefully','Test, improve and prepare for real use.']].map(([Icon,title,text],i)=><article key={title} data-aos="fade-up" data-aos-delay={i*90} className={`rounded-2xl border bg-white p-6 shadow-card ${i===0?'border-blue-100':i===1?'border-violet-100':'border-emerald-100'}`}><span className={`grid h-11 w-11 place-items-center rounded-xl text-white ${i===0?'bg-gradient-to-br from-brand-600 to-cyan-500':i===1?'bg-gradient-to-br from-violet-600 to-fuchsia-500':'bg-gradient-to-br from-accent-600 to-emerald-400'}`}><Icon size={21}/></span><h3 className="mt-5 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{text}</p></article>)}</div></div></section><CTA/></>
}
